### ISSUE TITLE
Wont work as of 06/25/2021

### ISSUE THREAD

**Issue by Khitomer86** [datvm/SubnauticaBZMods#1]
Was working fine yesterday. I have included the relevant log. no idea whats causing it not to load. I just get the red error when starting the game. 

[QModManager:ERROR] Invoking the specified entry method "Init" failed for mod "LVVitality"
[QModManager:ERROR] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not resolve type with token 01000031 (from typeref, class/assembly LukeMods.Common.ModUtils, LukeMods.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <fb001e01371b4adca20013e0ac763896>:0 
   --- End of inner exception stack trace ---
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00048] in <fb001e01371b4adca20013e0ac763896>:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in <fb001e01371b4adca20013e0ac763896>:0 
  at QModManager.Patching.QModPatchMethod.TryInvoke () [0x00034] in <7938525be2474c2d80cd441c8f217ed6>:0
[SubnauticaMap] Patched
[UnSlowSeaTruck] Patching v1.2.1
[UnSlowSeaTruck] Existing config file loaded.
[UnSlowSeaTruck] Configured WeightOverride: 0.0001
[UnSlowSeaTruck] Original HorsePowerModifier: 0.65
[UnSlowSeaTruck] Modified HorsePowerModifier: 0.7 (Less is faster)
[EasyCraft] Patched
[AdvancedInventory] Patched
[Info   :VersionChecker] Initialising...
[Info   :VersionChecker] Initialised in 25ms.
[Info   :SnapBuilder] Initialising SnapBuilder 1.4.1.0 for BelowZero...
[Info   :SnapBuilder] Harmony patches applied in 31ms.
[Info   :SnapBuilder] Initialised in 36ms.
[QuantumLockerEnhanced/INFO] Obtained values from config
[QuantumLockerEnhanced/INFO] Registered mod options
[QuantumLockerEnhanced/INFO] Patched successfully!
[PickupFullCarryalls] Patched successfully!
[PickupFullCarryalls] Obtained values from config
[PickupFullCarryalls] Registered mod options
[BetterThumper:INFO] BetterThumper Patched
[SlotExtenderZero/LOG] Configuration loaded.
[SlotExtenderZero/LOG] Session slotID's created.
[SlotExtenderZero/LOG] Equipment slot mapping Patched!
[SMLHelper/Info] Added 234 TechTypes succesfully into the game.
[SMLHelper/Info] Added 1 CraftTreeTypes succesfully into the game.
[SMLHelper/Info] Added 0 PingTypes succesfully into the game.
[SMLHelper/Info] Finished known TechCategory exclusion. 0 IDs were added in ban list.
[SMLHelper/Info] Added 0 TechCategorys succesfully into the game.
[SMLHelper/Info] Finished known TechGroup exclusion. 0 IDs were added in ban list.
[SMLHelper/Info] Added 0 TechGroups succesfully into the game.
[SMLHelper/Info] Finished known BackgroundType exclusion. 0 IDs were added in ban list.
[SMLHelper/Info] Added 0 BackgroundTypes succesfully into the game.
[SMLHelper/Info] Added 3 middle click actions.
[SMLHelper/Info] Extra item info set to: Mod name (default)
[QModManager:INFO] Finished loading QModManager. Loaded 46 mods.
[QModManager:ERROR] A total of 1 mods failed to load
[QModManager:WARN] Some mods are using an old version of harmony! This will NOT cause any problems, but it's not recommended:
- Prawn Suit Grappling Arm Upgrade (PrawnSuitGrapplingArmUpgrade)
- UI Tweaks (UITweaks)
- DataBoxScannerFix (DataBoxScannerFix)
[QModManager:ERROR] The following mods failed during patching:
- Vitality (LVVitality)
Object reference not set to an instance of an object
uGUI_SceneControllerDisconnected.Initialize()
Telemetry session started.
Waiting for options to load...
RegisterSaveGame: load operation for options was not successful.
Waiting for slot0000 to load...
RegisterSaveGame: Loading GameInfo for slot0000
Loading game settings

**Comment by datvm** [comment]
Ah thanks I am aware of this now, somehow my common DLL is not working, will post an update soon.

**Comment by datvm** [comment]
Pushed out an update to v1.1. Should work now, thanks :)

https://www.nexusmods.com/subnauticabelowzero/mods/207?tab=posts&BH=0
